gallery/urls.py
from django.conf.urls import url
from . import views
from . import feeds

urlpatterns = [
    url(r'^$', views.gallery_front, name='gallery.front'),
    url(r'^albums/$', views.album_list, name='album.list'),
    url(r'^album/([0-9]+)/$', views.album_detail, name='album.detail'),
    url(r'^photos/$', views.photo_list, name='photo.list'),
    url(r'^photos/([-\s\w]+)/$', views.photo_list, name='photo.list'),
    url(r'^photo/([0-9]+)/$', views.photo_detail, name='photo.detail'),
    url(r'^siteimages/all/rss/$', feeds.LatestPhotosRssFeed()),
    url(r'^siteimages/all/atom/$', feeds.LatestPhotosAtomFeed()),
    url(r'^siteimages/featured/rss/$', feeds.LatestFeaturedPhotosRssFeed()),
    url(r'^siteimages/featured/atom/$', feeds.LatestFeaturedPhotosAtomFeed()),
]

groundup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView

from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.flatpages import views

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from newsroom.models import Article
from newsroom.models import Author

from gallery.models import Photograph

from filebrowser.sites import site

from ajax_select import urls as ajax_select_urls

article_dict = {
    'queryset': Article.objects.published(),
    'date_field': 'published',
}

author_dict = {
    'queryset': Author.objects.all(),
    'date_field': 'modified',
}

photo_dict = {
    'queryset': Photograph.objects.all(),
    'date_field': 'modified',
}

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^admin/login/$', RedirectView.as_view(url='/accounts/login/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imagegallery/', include('gallery.urls')),
    url(r'^', include('newsroom.urls')),
    url(r'^', include('payment.urls')),
    url(r'^', include('letters.urls')),
    url(r'^', include('security.urls')),
    url(r'^', include('allauth_2fa.urls')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps':
         {'articles': GenericSitemap(article_dict,
                                     priority=0.5),
          'authors': GenericSitemap(author_dict,
                                    priority=0.5,
                                    changefreq='weekly'),
          'photos': GenericSitemap(photo_dict,
                                   priority=0.5),
          'flatpages': FlatPageSitemap}},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^cache/', include('clearcache.urls', namespace="cache")),
    url(r'^robots\.txt',
        TemplateView.as_view(template_name='robots.txt',
                             content_type='text/plain'),
        name='robots.txt'),
    url(r'^404testing',
        TemplateView.as_view(template_name='404.html'),
        name='test404'),
    url(r'^500testing',
        TemplateView.as_view(template_name='500.html'),
        name='test500'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

letters/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from .views import write_letter


urlpatterns = [
    url(r'^letter/([0-9]+)/$', write_letter, name='letter_to_editor'),
    url(r'^thanks/$', TemplateView.as_view(
        template_name='letters/letter_thanks.html'),
        name='letter_thanks'),
]

payment/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^invoices/$', views.invoice_list,
        name="invoice.list"),

    url(r'^invoices/([0-9]+)/([0-9]+)/([0-9]+)$', views.invoice_list,
        name="invoice.list"),

    url(r'^invoices/([0-9]+)-([0-9]+)$', views.invoice_detail,
        name="invoice.detail"),

    url(r'^invoices/print/([0-9]+)-([0-9]+)$', views.invoice_print,
        name="invoice.print"),

    url(r'^commissions/([0-9]+)$', views.commission_detail,
        name="commissions.detail"),

    url(r'^commissions/add$', views.commission_detail,
        name="commissions.detail.add"),
]

payment/models.py
from decimal import Decimal

from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Max
from django.utils import timezone
from filebrowser.fields import FileBrowseField
from newsroom.models import Article, Author

INVOICE_STATUS_CHOICES = (
    ("-", "Invoice being prepared by editor"),
    ("0", "Reporter needs to approve"),
    ("1", "Queried by reporter"),
    ("2", "Approved by reporter"),
    ("3", "Approved by editor"),
    ("4", "Paid"),
    ("5", "Deleted"),
)

COMMISSION_DESCRIPTION_CHOICES = (
    ("", ""),
    ("Article author", "Article author"),
    ("Photographs", "Photographs"),
    ("Article cancellation fee", "Article cancellation fee"),
    ("Expenses", "Expenses"),
    ("Editing", "Editing"),
    ("Subediting", "Subediting"),
    ("Consulting", "Consulting"),
    ("Administration", "Administration"),
    ("Sundry", "Sundry"),
)


class Fund(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name.upper()

    class Meta:
        ordering = ['name', ]


EXTENSIONS = [".jpg", ".pdf", ".doc", ".docx", ".odt", ".xls", ".xlsx",
              ".zip", ".JPG", ".PDF", ".DOC", ".DOCX"]


def set_corresponding_vals(fromobj, to):
    to.identification = fromobj.identification
    to.dob = fromobj.dob
    to.address = fromobj.address
    to.bank_name = fromobj.bank_name
    to.bank_account_number = fromobj.bank_account_number
    to.bank_branch_name = fromobj.bank_branch_name
    to.bank_branch_code = fromobj.bank_branch_code
    to.swift_code = fromobj.swift_code
    to.iban = fromobj.iban
    to.tax_no = fromobj.tax_no
    to.tax_percent = fromobj.tax_percent
    to.vat = fromobj.vat


class Invoice(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    invoice_num = models.IntegerField(default=0)
    # Fields whose default values are taken from Author
    identification = models.CharField(max_length=20, blank=True,
                                      help_text="SA ID, passport or some form "
                                      "of official identification")
    dob = models.DateField(blank=True, null=True, verbose_name="date of birth",
                           help_text="Required by SARS")
    address = models.TextField(blank=True,
                               help_text="Required by SARS")
    bank_name = models.CharField(max_length=20, blank=True)
    bank_account_number = models.CharField(max_length=20,
                                           verbose_name="account",
                                           blank=True)
    bank_account_type = models.CharField(max_length=20,
                                         verbose_name="account type",
                                         default="CURRENT")
    bank_branch_name = models.CharField(max_length=20, blank=True,
                                        verbose_name="branch name",
                                        help_text="Unnecessary for Capitec, "
                                        "FNB, Standard, Nedbank and Absa")
    bank_branch_code = models.CharField(max_length=20, blank=True,
                                        verbose_name="branch code",
                                        help_text="Unnecessary for Capitec, "
                                        "FNB, Standard, Nedbank and Absa")
    swift_code = models.CharField(max_length=12, blank=True,
                                  help_text="Only relevant for banks "
                                  "outside SA")
    iban = models.CharField(max_length=34, blank=True,
                            help_text="Only relevant for banks outside SA")
    tax_no = models.CharField(max_length=50, blank=True,
                              verbose_name="tax number",
                              help_text="Necessary for SARS.")
    tax_percent = models.DecimalField(max_digits=2, decimal_places=0,
                                      default=25,
                                      verbose_name="PAYE %",
                                      help_text="Unless you have "
                                      "a tax directive "
                                      "we have to deduct 25% PAYE")
    vat = models.DecimalField(max_digits=2, decimal_places=0, default=0,
                              verbose_name="VAT %",
                              help_text="If you are VAT registered "
                              "set this to 15 else leave at 0")
    ####
    # paid = models.BooleanField(default=False)
    amount_paid = models.DecimalField(max_digits=8,
                                      decimal_places=2, default=0.00,
                                      verbose_name="amount")
    tax_paid = models.DecimalField(max_digits=8,
                                   decimal_places=2, default=0.00)
    vat_paid = models.DecimalField(max_digits=8,
                                   decimal_places=2, default=0.00)
    invoice = FileBrowseField(max_length=200,
                              directory="commissions/invoices/",
                              blank=True, extensions=EXTENSIONS)
    proof = FileBrowseField(max_length=200, directory="commissions/proofs/",
                            blank=True, extensions=EXTENSIONS)
    status = models.CharField(max_length=2, choices=INVOICE_STATUS_CHOICES,
                              default="-")
    notes = models.TextField(blank=True)
    query = models.TextField(blank=True, max_length=3000,
                             help_text="Explain your query "
                             "here if you have one")
    date_time_reporter_approved = models.DateTimeField(null=True, blank=True,
                                                       editable=False)
    date_time_editor_approved = models.DateTimeField(null=True, blank=True,
                                                     editable=False)
    date_time_processed = models.DateTimeField(null=True, blank=True,
                                               editable=False)
    date_notified_payment = models.DateTimeField(null=True, blank=True,
                                                 editable=False)
    our_reference = models.CharField(max_length=20, blank=True)
    their_reference = models.CharField(max_length=20, blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    def calc_payment(self):
        commissions = Commission.objects.for_authors().\
                      filter(invoice=self)
        total_uncorrected = Decimal(0.00)
        total_paid = Decimal(0.00)
        total_tax = Decimal(0.00)
        total_vat = Decimal(0.00)
        for commission in commissions:
            (due, vat, tax, uncorrected) = commission.calc_payment()
            total_paid = total_paid + due
            total_vat = total_vat + vat
            total_tax = total_tax + tax
            total_uncorrected = total_uncorrected + uncorrected
        self.amount_paid = total_paid
        self.vat_paid = total_vat
        self.tax_paid = total_tax
        return (self.amount_paid, self.vat_paid,
                self.tax_paid, total_uncorrected,)

    def __str__(self):
        return str(self.author.pk) + "-" + str(self.invoice_num) + " - " + \
            str(self.author) + " - " + self.get_status_display()

    def get_absolute_url(self):
        return reverse('invoice.detail', args=[self.author.pk,
                                               self.invoice_num])

    def short_string(self):
        return str(self.author.pk) + "-" + str(self.invoice_num)

    def save(self, *args, **kwargs):
        if self.status == "2":  # Reporter has approved
            if self.date_time_reporter_approved is None:
                self.date_time_reporter_approved = timezone.now()
        if self.status == "3":  # Editor has approved
            if self.date_time_editor_approved is None:
                self.date_time_editor_approved = timezone.now()
        if self.status == "4":  # Invoice has been paid
            if self.date_time_processed is None:
                self.date_time_processed = timezone.now()
        self.calc_payment()
        super(Invoice, self).save(*args, **kwargs)
        set_corresponding_vals(self, self.author)
        self.author.save()

    @staticmethod
    def create_invoice(author):
        max_invoice = Invoice.objects.filter(author=author).\
                  aggregate(Max('invoice_num'))
        if max_invoice["invoice_num__max"] is None:
            invoice_num = 1
        else:
            invoice_num = max_invoice["invoice_num__max"] + 1
        invoice = Invoice()
        invoice.author = author
        invoice.invoice_num = invoice_num
        set_corresponding_vals(author, invoice)
        invoice.save()
        return invoice

    @staticmethod
    def get_open_invoice_for_author(author):
        invoices = Invoice.objects.filter(author=author).\
                                   filter(status__lte="0")
        if len(invoices) == 0:
            invoice = Invoice.create_invoice(author)
        else:
            invoice = invoices[0]
            if invoice.status == "0":
                invoice.status = "-"
                invoice.save()
        return invoice

    class Meta:
        ordering = ['status', '-modified', ]
        unique_together = ['author', 'invoice_num', ]


class CommissionQuerySet(models.QuerySet):

    def for_staff(self):
        return self.filter(deleted=False)

    def for_authors(self):
        return self.for_staff().filter(fund__isnull=False)


# Should have been named "Payment" hence the verbose_name
class Commission(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, blank=True, null=True,
                                on_delete=models.CASCADE)
    description = models.CharField(max_length=50, blank=True,

payment/forms.py
from ajax_select.fields import AutoCompleteSelectField
from django import forms
from django.forms import ModelForm
from newsroom.models import Article, Author
from payment.models import Commission, Invoice

BIRTH_YEAR_CHOICES = range(1920,2016)

class InvoiceStaffForm(ModelForm):
    dob = forms.DateField(widget=
                          forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES),
                          label="Date of birth",
                          required=False)
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': '4'}),
                              required=False,
                              help_text="Required by SARS")

    class Meta:
        model = Invoice
        fields = ['identification', 'dob', 'address',
                   'bank_name', 'bank_account_number',
                   'bank_account_type', 'bank_branch_name', 'bank_branch_code',
                   'swift_code', 'iban', 'tax_no', 'tax_percent', 'vat',
                   'query',
        ]

class InvoiceForm(InvoiceStaffForm):
    identification = forms.CharField(max_length=20, required=True,
                                     help_text=
                                     "SA ID, passport or some form "
                                     "of official identification")
    dob = forms.DateField(widget=
                          forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES),
                          label="Date of birth",
                          required=True)
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': '4'}),
                              required=True,
                              help_text="Required by SARS")

    bank_name = forms.CharField(max_length=20, required=True)
    bank_account_number = forms.CharField(max_length=20, required=True)

    def clean(self):
        cleaned_data = super(InvoiceForm, self).clean()
        query = cleaned_data.get("query")
        if "query_button" in self.data and query == "":
            self.add_error("query",
                           "Please explain why you're querying "
                           "the invoice")

class CommissionForm(ModelForm):
    author = AutoCompleteSelectField("authors", required=False, help_text=None)
    article = AutoCompleteSelectField('articles', required=False,
                                      help_text=None)

    def clean_author(self):
        data = self.cleaned_data['author']
        if data is None:
            raise forms.ValidationError("Please enter an author")
        return data

    class Meta:
        model = Commission
        fields = ['author', 'article', 'description', 'notes',
                  'commission_due', 'taxable', 'vatable', 'fund', ]

payment/templates/payment/commission_detail.html
{% extends "base_20161106.html" %}

{% block title %}
    Commission {{block.super}}
{% endblock %}

{% block content %}
    {{ form.media }}

    <div id="commission-detail">
        {% if pk %}
            {% with invoice=commission.invoice %}
                <h2>Edit commission {{pk}} for
                    <a href="{% url 'invoice.detail' invoice.author.pk invoice.invoice_num %}">
                        Invoice: {{invoice.short_string}}</h2>
                    </a>
            {% endwith %}
        {% else %}
            <h2>New commission</h2>
        {% endif %}
        <form action="{% if pk %}
                      {% url 'commissions.detail' pk %}
        {% else %}
                      {% url 'commissions.detail.add' %}
        {% endif %}"
              method="post">
            {% csrf_token %}
            <table>
                {{form.as_table}}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Save" />
                    </td>
                </tr>
            </table>

        </form>
    </div>
{% endblock %}

payment/templates/payment/invoice_detail.html
{% extends "base_20161106.html" %}

{% block title %}
    Invoice {{block.super}}
{% endblock %}


{% block css-override %}
    {% if can_edit == False %}
        <style>
         .helptext {display: none;}
        </style>
    {% endif %}
    {% if print_view == True %}
        <style>
         #id_query {display: none;}
         label[for="id_query"] {display:none;}
        </style>
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

{% block admin-area %}
    {% if print_view %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

{% block banner %}
    {% if print_view %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

{% block messages %}
    {% if print_view %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}


{% block content %}
    <h1>Invoice #{{invoice.short_string}} for {{invoice.author}}</h1>
    <h2>
        {% if invoice.status == "-" %}
            This invoice is being prepared by the editor
        {% elif invoice.status == "0" %}
            {{invoice.author}} needs to approve this invoice
        {% elif invoice.status == "1" %}
            {{invoice.author}} has queried this invoice
        {% elif invoice.status == "2" %}
            {{invoice.author}} has approved this invoice
        {% elif invoice.status == "3" %}
            The editors have approved this invoice for payment
        {% elif invoice.status == "4" %}
            Paid on {{invoice.date_time_processed|date:"j M Y"}}
        {% elif invoice.status == "5" %}
            This invoice has been marked for deletion.
        {% endif %}
    </h2>
    <form
        action="{% url 'invoice.detail' invoice.author.pk invoice.invoice_num %}"
        method="post">
    <div class="container">
        <div class="row">
	    <div class="col-xs-12 col-md-6">

                    {% if can_edit == False %}<fieldset disabled>
                    {% endif %}
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <table class="table table-striped table-condensed"
                           id="invoice-form">

                        {{ form.as_table }}
                        {% if can_edit %}
                        <tr>
                            <td>
                                {% if can_edit_commissions %}
                                    <input type="submit"
                                           name="update_button"
                                           class="btn btn-info"
                                           value="Update details" />
                                    &nbsp;
                                    {% if can_edit_commissions %}
                                        <br /><br />
                                        <input type="submit"
                                               name="delete_button"
                                               class="btn btn-danger"
                                               value="Delete" />
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td>
                                {% if not staff_view %}
                                    <input type="submit"
                                           name="query_button"
                                           class="btn btn-warning"
                                           value="Query invoice" />
                                    &nbsp;
                                    <input type="submit"
                                           name="pay_button"
                                           class="btn btn-primary"
                                           value="Please pay invoice" />
                                {% else %}
                                    {% if can_edit_commissions %}
                                        <input type="submit"
                                               name="begin_button"
                                               class="btn"
                                               value="Begin" />
                                        &nbsp;
                                        <input type="submit"
                                               name="return_button"
                                               class="btn
                                                      {% if invoice.status == "-" or invoice.status == "1" %}
                                                      btn-primary
                                                      {% endif %}"
                                               value="Author" />
                                        &nbsp;
                                        <input type="submit"
                                               name="approve_button"
                                               class="btn
                                                      {% if invoice.status == "2" %}
                                                      btn-primary
                                                      {% endif %}"
                                               value="Approve" />
                                        &nbsp;
                                    {% endif %}
                                    <input type="submit"
                                           name="paid_button"
                                           class="btn
                                                  {% if invoice.status == "3" %}
                                                  btn-primary
                                                  {% endif %}""
                                           value="Paid" />
                                {% endif %}
                            </td>
                        </tr>
                        {% endif %}
                    </table>
                    {% if can_edit == False %}</fieldset>{% endif %}

            </div>
	    <div class="col-xs-12 col-md-6">
                {% include "payment/invoice_table.html" %}
                {% if not print_view %}
                    <a href="{% url "invoice.list" %}">INVOICES</a> |
                    <a href="{% url "invoice.print" invoice.author.pk invoice.invoice_num %}"
                       target="_blank"
                    >
                        PRINT
                    </a>
                    {% if can_edit_commissions %}
                        |
                        <a href="{% url 'commissions.detail.add' %}?author={{invoice.author.pk}}"
                           target="_blank">
                            ADD COMMISSION
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </form>
    <hr />
{% endblock %}

{% block footer %}
    {% if print_view %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

{% block javascript-includes %}
    {% if print_view %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

payment/templates/payment/invoice_list.html
{% extends "base_20161106.html" %}
{% load humanize %}

{% block title %}
    Invoices {{block.super}}
{% endblock %}

{% block content %}

    <h1>Invoices
        {% if not staff_view %}
            for {{request.user.first_name}} {{request.user.last_name}}
        {% else %}
            for
            {% if this_month %}
                {{this_month|date:"F Y"}}
            {% else %}
                all time
            {% endif %}
        {% endif %}
    </h1>

    {% if staff_view %}
        <p>
            Paid: R{{total_paid_for_month|floatformat:"2"|intcomma}}
            {% if total_outstanding_for_month %}
                | Outstanding: R{{total_outstanding_for_month|floatformat:"2"|intcomma}}
            {% endif %}
            {% if total_for_month %}
                | Total: R{{total_for_month|floatformat:"2"|intcomma}}
            {% endif %}
        </p>
        <p>
            {% if this_month %}
                <a href="{% url "invoice.list" previous_month.year previous_month.month 0 %}">
                    Previous: {{previous_month|date:"F Y"}}
                </a>
                &nbsp;|&nbsp;
                <a href="{% url "invoice.list" next_month.year next_month.month 0 %}">
                    Next: {{next_month|date:"F Y"}}
                </a>
                &nbsp;|&nbsp;
                <a href="{% url "invoice.list" 0 0 0 %}">
                    All
                </a>
            {% else %}
                <a href="{% url "invoice.list" next_month.year next_month.month 0 %}">
                    Go to latest month: {{next_month|date:"F Y"}}
                </a>
            {% endif %}
            {% if author %}
                &nbsp;&nbsp;&nbsp;&nbsp;Author: {{author}}
            {% endif %}
        </p>
    {% endif %}

    <table class="table" id="invoice-table">
        <tr>
            <th>#</th>
            <th>Status</th>
            <th >Before tax & VAT</th>
            <th >Tax</th>
            <th >Vat</th>
            <th >Due</th>
            {% if staff_view %}
                <th>Name</th>
            {% endif %}
        </tr>
        {% for invoice in invoices %}
            {% with invoice.calc_payment as payment %}
                {% if staff_view or payment.3 > 0.00 %}
                    <tr>
                        <td>
                            <a href="{% url "invoice.detail" invoice.author.pk invoice.invoice_num %}">

                                    {{invoice.short_string}}

                            </a>
                        </td>
                        <td>
                            <span class="status{{invoice.status}}">
                                {{invoice.get_status_display}}
                                {% if invoice.status == "4" %}
                                    on {{invoice.date_time_processed|date:"j M Y"}}
                                {% endif %}
                            </span>
                        </td>

                        <td>R{{payment.3|floatformat:2}}</td>
                        <td>R{{payment.2|floatformat:2}}</td>
                        <td>R{{payment.1|floatformat:2}}</td>
                        <td>R{{payment.0|floatformat:2}}</td>
                        {% if staff_view %}
                            <td>
                                <a href="{%  url 'invoice.list' 0 0 invoice.author.pk %}">
                                    {{invoice.author}}
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% endwith %}
        {% endfor %}
    </table>

{% endblock %}