gallery/urls.py
from django.conf.urls import url
from . import views
from . import feeds

urlpatterns = [
    url(r'^$', views.gallery_front, name='gallery.front'),
    url(r'^albums/$', views.album_list, name='album.list'),
    url(r'^album/([0-9]+)/$', views.album_detail, name='album.detail'),
    url(r'^photos/$', views.photo_list, name='photo.list'),
    url(r'^photos/([-\s\w]+)/$', views.photo_list, name='photo.list'),
    url(r'^photo/([0-9]+)/$', views.photo_detail, name='photo.detail'),
    url(r'^siteimages/all/rss/$', feeds.LatestPhotosRssFeed()),
    url(r'^siteimages/all/atom/$', feeds.LatestPhotosAtomFeed()),
    url(r'^siteimages/featured/rss/$', feeds.LatestFeaturedPhotosRssFeed()),
    url(r'^siteimages/featured/atom/$', feeds.LatestFeaturedPhotosAtomFeed()),
]

groundup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView

from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.flatpages import views

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from newsroom.models import Article
from newsroom.models import Author

from gallery.models import Photograph

from filebrowser.sites import site

from ajax_select import urls as ajax_select_urls

article_dict = {
    'queryset': Article.objects.published(),
    'date_field': 'published',
}

author_dict = {
    'queryset': Author.objects.all(),
    'date_field': 'modified',
}

photo_dict = {
    'queryset': Photograph.objects.all(),
    'date_field': 'modified',
}

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^admin/login/$', RedirectView.as_view(url='/accounts/login/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imagegallery/', include('gallery.urls')),
    url(r'^', include('newsroom.urls')),
    url(r'^', include('payment.urls')),
    url(r'^', include('letters.urls')),
    url(r'^', include('security.urls')),
    url(r'^', include('allauth_2fa.urls')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps':
         {'articles': GenericSitemap(article_dict,
                                     priority=0.5),
          'authors': GenericSitemap(author_dict,
                                    priority=0.5,
                                    changefreq='weekly'),
          'photos': GenericSitemap(photo_dict,
                                   priority=0.5),
          'flatpages': FlatPageSitemap}},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^cache/', include('clearcache.urls', namespace="cache")),
    url(r'^robots\.txt',
        TemplateView.as_view(template_name='robots.txt',
                             content_type='text/plain'),
        name='robots.txt'),
    url(r'^404testing',
        TemplateView.as_view(template_name='404.html'),
        name='test404'),
    url(r'^500testing',
        TemplateView.as_view(template_name='500.html'),
        name='test500'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'^(?P<url>.*/)$', views.flatpage),
]

letters/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from .views import write_letter


urlpatterns = [
    url(r'^letter/([0-9]+)/$', write_letter, name='letter_to_editor'),
    url(r'^thanks/$', TemplateView.as_view(
        template_name='letters/letter_thanks.html'),
        name='letter_thanks'),
]

newsroom/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView

from . import feeds, settings, views
from .utils import cache_except_staff


urlpatterns = [
    url(r'^$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.home_page_view),
        name='home'),

    # url(r'^search/$', views.search, name='article.search'),

    url(r'^advanced_search/$', views.advanced_search, name='advanced.search'),

    url(r'^category/opinion_and_analysis/$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.OpinionAnalysisList.as_view()),
        name='article.opinion_analysis'),

    url(r'^category/$', views.CategoryList.as_view(),
        name="category.list"),

    url(r'^category/([-\s\w]+)/$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.CategoryDetail.as_view()), name='category.detail'),

    url(r'^region/$', views.RegionList.as_view(),
        name="region.list"),

    url(r'^region/(.*)$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.RegionDetail.as_view()), name='region.detail'),

    url(r'^topic/$', views.TopicList.as_view(),
        name="topic.list"),

    url(r'^topic/([-\s\w]+)/$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.TopicDetail.as_view()), name='topic.detail'),

    url(r'^user/$', views.account_profile,
        name="user.profile"),

    ###############################
    # Article list generate

    url(r'^generate_article_list/$',
        views.generate_article_list, name='generate_article_list'),

    ###############################
    # Old feature article redirects
    url(r'^article/redhills-ruins-cape-towns-forgotten-district-six_2043/$',
        RedirectView.as_view(url='/media/features/redhill/redhill_2043.html',
                             permanent=False)),

    url(r'^article/mpumalanga-crisis-why-nobody-listening_2236/$',
        RedirectView.as_view(url='/media/features/mpumalanga/mpumalanga_0002.html',
                             permanent=False)),

    url(r'^article/will-i-make-money-today-waiting-work-side-road_2245/$',
        RedirectView.as_view(url='/media/features/menatsideofroad/menatroadside_0003.html',
                             permanent=False)),

    url(r'^article/long-trek-education-city-students_2400/$',
        RedirectView.as_view(url='/media/features/westlake/westlake_0004.html',
                             permanent=False)),

    url(r'^article/house-full-faeces-khayelitsha_2447/$',
        RedirectView.as_view(url='/media/features/faeces/house_faeces_0005.html',
                             permanent=False)),

    url(r'^article/fishing-black-river_2514/$',
        RedirectView.as_view(url='/media/features/blackriver/blackriver_0006.html',
                             permanent=False)),

    url(r'^article/ocean-view-fisher-blues-part-one_2657/$',
        RedirectView.as_view(url='/media/features/daff/daff_1_0008.html',
                             permanent=False)),

    url(r'^article/ocean-view-fisher-blues-part-two_2658/$',
        RedirectView.as_view(url='/media/features/daff/daff_2_0008.html',
                             permanent=False)),

    url(r'^article/how-free-state-health-system-being-destroyed_2722/$',
        RedirectView.as_view(url='/media/features/freestatehealth/freestatehealth.html',
                             permanent=False)),

    url(r'^article/tee-along-n2_2761/$',
        RedirectView.as_view(url='/media/features/n2golfer/n2golfer.html',
                             permanent=False)),

    url(r'^article/living-hole-ground-district-six_2767/$',
        RedirectView.as_view(url='/media/features/holeground/holeground.html',
                             permanent=False)),

    url(r'^article/rhodes-falls_2824/$',
        RedirectView.as_view(url='/media/features/RhodesFalls/rhodesfalls.html',
                             permanent=False)),

    url(r'^article/lost-karretjie-people-karoo_2825/$',
        RedirectView.as_view(url='/media/features/karretjie/karretjiepeople.html',
                             permanent=False)),

    url(r'^article/beautiful-photos-old-cape-town_2869/$',
        RedirectView.as_view(url='/media/features/oldctphotos/oldctphotos.html',
                                      permanent=False)),

    url(r'^article/custodian-baths_2931/$',
        RedirectView.as_view(url='/media/features/longstreet/longstreet.html',
                             permanent=False)),

    url(r'^article/hout-bays-scrapyard-sculptors_2955/$',
        RedirectView.as_view(url='/media/features/houtbaysculptors/houtbaysculptors.html',
                             permanent=False)),

    url(r'^article/when-government-gentrifies-case-de-waal-drive-flats_2985/$',
        RedirectView.as_view(url='/media/features/gentrification/gentrification.html',
                             permanent=False)),

    url(r'^article/waiting-waiting-and-waiting-doctor_3064/$',
        RedirectView.as_view(url='/media/features/clinicqueues/clinicqueues_0016.html',
                             permanent=False)),

    url(r'^article/battle-over-bleak-houses-citys-edge_3078/$',
        RedirectView.as_view(url='/media/features/wolwerivier/wolwerivier_0017.html',
                             permanent=False)),

    url(r'^article/murder-long-street-congolese-bouncers-and-private-security-industry_3092/$',
        RedirectView.as_view(url='/media/features/murderlongstreet/murderlongstreet_0018.html',
                             permanent=False)),

    url(r'^article/incredible-journey-how-lady-lost-mongrel-found-her-way-home_3104/$',
        RedirectView.as_view(url='/media/features/incrediblejourney/incrediblejourney_0019.html',
                             permanent=False)),

    url(r'^article/why-hout-bay-fishermen-die-making-living_3200/$',
        RedirectView.as_view(url='/media/features/hangberg/hangberg_0020.html',
                             permanent=False)),


    url(r'^article/cape-towns-pakistani-cellphone-connection_3247/$',
        RedirectView.as_view(url='/media/features/cellphones/cellphones_0021.html',
                             permanent=False)),

    url(r'^article/long-battle-get-mines-cough_3271/$',
        RedirectView.as_view(url='/media/features/silicosis/silicosis_0022.html',
                             permanent=False)),

    url(r'^article/student-fees-facts-figures-and-observations_3423/$',
        RedirectView.as_view(url='/media/features/studentfees/studentfees_0023.html',
                             permanent=False)),

    url(r'^article/photos-and-video-students-uwc-march-feesmustfall_3433/$',
        RedirectView.as_view(url='/media/features/uwcmarch/uwcmarch_0024.html',
                             permanent=False)),

    url(r'^article/feesmustfall-protest-union-buildings-photo-time-line-what-happened_3434/$',
        RedirectView.as_view(url='/media/features/unionbuildings/unionbuildings_0025.html',
                             permanent=False)),


    url(r'^article/toilet-collectors_3462/$',
        RedirectView.as_view(url='/media/features/potapota/potapota_0026.html',
                             permanent=False)),

    url(r'^article/2015-photos_3606/$',
        RedirectView.as_view(url='/media/features/2015photos/2015photos.html',
                             permanent=False)),

    # Some old flatpages

    url(r'^about-groundup/$',
        RedirectView.as_view(url='/about/',
                             permanent=True)),

    url(r'^content/contact-us/$',
        RedirectView.as_view(url='/',
                             permanent=True)),

    url(r'^get-your-opinion-piece-published/$',
        RedirectView.as_view(url='/publish/',
                             permanent=True)),



    ###############################

    url(r'^article/(?P<slug>[-\w]+)/$',
        cache_except_staff(
            decorator=cache_page(settings.CACHE_PERIOD,
                                 key_prefix='article'))
        (views.article_detail), name='article.detail'),

    url(r'^copy_article/(?P<slug>[-\w]+)/$',
        views.copy_article, name='article.copy'),

    url(r'^article_concurrent$',
        views.check_concurrent_edit, name='article.concurrent_check'),

    url(r'^author/$', views.AuthorList.as_view(),
        name="author.list"),

    url(r'^author/([0-9]+)/$',
        cache_except_staff(decorator=cache_page(settings.CACHE_PERIOD))
        (views.AuthorDetail.as_view()), name='author.detail'),

    url(r'^sites/default/(?P<path>.*)$',
        views.RedirectOldImages.as_view(), name='old_image.redirect'),

    url(r'^features/(?P<path>.*)$',
        views.RedirectHandConstructedFeatures.as_view(),
        name='features.redirect'),

    ####################################
    # Redirect /content/ to /article

    url(r'^content/(?P<path>.*)$',
        views.RedirectContentToArticle.as_view(), name='content.redirect'),

    url(r'^photoessay/(?P<path>.*)$',
        views.RedirectContentToArticle.as_view(), name='content.redirect'),

    url(r'^gallery/(?P<path>.*)$',
        views.RedirectContentToArticle.as_view(), name='content.redirect'),


    ####################################

    url(r'^sitenews/rss/$', feeds.LatestArticlesRssFeed()),
    url(r'^sitenews/atom/$', feeds.LatestArticlesAtomFeed()),
]

newsroom/forms.py
from django import forms

from . import models, utils


SEARCH_TYPES=[('article', 'Articles'),
             ('image', 'Images'),
             ('both', 'Both')]

class ArticleListForm(forms.Form):
    date_from = forms.DateTimeField()
    date_to = forms.DateTimeField(required=False)


class ArticleForm(forms.ModelForm):

    def clean(self, *args, **kwargs):
        if self.cleaned_data["use_editor"]:
            body = self.cleaned_data["body"]
            self.cleaned_data["body"] = utils.replaceBadHtmlWithGood(body)

        super(ArticleForm, self).clean(*args, **kwargs)

    class Meta:
        model = models.Article
        fields = ['title', 'subtitle', 'use_editor',
                  'primary_image_caption', 'body', 'user', 'version', ]


class AdvancedSearchForm(forms.Form):
    RESULTS_PER_PAGE = [(10, '10 Results Per Page'),
                        (20, '20 Results Per Page'),
                        (50, '50 Results Per Page'),
                        (100, '100 Results Per Page')]
    
    adv_search = forms.CharField(label="Search Term...",
                                 widget=forms.TextInput(attrs={'placeholder': 'Search...'}),
                                 required=False)
    search_type = forms.ChoiceField(choices=SEARCH_TYPES,
                                    widget=forms.RadioSelect(),
                                    required=False,
                                    initial='both')
    author = forms.ModelChoiceField(queryset=models.Author.objects.all().order_by('first_names'),
                                    required=False)
    first_author = forms.BooleanField(label="First Author Only", required=False)
    category = forms.ModelChoiceField(queryset=models.Category.objects.all(), required=False)
    topics = forms.ModelChoiceField(queryset=models.Topic.objects.all(), required=False)
    date_from = forms.DateTimeField(widget=forms.DateInput(attrs={'data-toggle': 'datepicker'}),
                                    required=False,
                                    input_formats=['%d/%m/%Y'])
    date_to = forms.DateTimeField(widget=forms.DateInput(attrs={'data-toggle': 'datepicker'}),
                                  required=False,
                                  input_formats=['%d/%m/%Y'])
    results_per_page = forms.ChoiceField(choices=RESULTS_PER_PAGE, required=False)

socialmedia/views.py
from django.shortcuts import render

# Create your views here.

newsroom/templates/newsroom/account_profile.html
{% extends "account/base.html" %}
{% load account socialaccount %}



{% block content %}
{% if request.user.is_authenticated %}
    <h1>{{user.first_name}} {{user.last_name}}</h1>
    <ul>
        {% if user.author.freelancer  %}
            <li>
                <a href='{% url "invoice.list" %}'>Invoices</a>
            </li>
        {% endif %}
        <li><a href="{% url "account_change_password" %}">
            Change password</a>
        </li>
        <li><a href="{% url "two-factor-setup" %}">
            Setup two-factor authentication</a>
        </li>
        <li><a href="{% url "account_logout" %}">
            Logout</a>
        </li>
    </ul>


{% else %}
    <p>Please <a href="{% url 'account_login' %}">login</a>.</p>
{% endif %}

{% endblock %}

newsroom/templates/newsroom/advert_acme.html
<h3 class="advert-title">Advert from Google ADX</h3>

<script type="text/javascript"><!--
                               google_ad_client = "ca-pub-6820505261750827";
 /* acme_groundup_300_250 */
 google_ad_slot = "3244286457";
 google_ad_width = 300;
 google_ad_height = 250;
 //-->
</script>
<script type="text/javascript"
        src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

newsroom/templates/newsroom/article_comments.html
<div id="comments">
    <div class="panel-group">
      <div class="panel panel-default">
        <a class="article__comment__link" data-toggle="collapse" href="#collapse1">
	  <div class="panel-heading article__comment__button">
	    <h2 class="panel-title article__comment__title">
	      <i class="fa fa-plus" aria-hidden="true"></i>
	      Reader comments
	    </h2>
	  </div>
        </a>
	    <div id="collapse1" class="panel-collapse
				       {% if article.collapse_comments %}
				       collapse {% endif %}">
		<div class="panel-body">
		    <div id="comment-policy">
			You are welcome to comment. Please <a href="/code-decency">read our policy</a>.
		    </div>
		    <div id="disqus_thread">
			<script type="text/javascript">
			 var disqus_shortname = 'groundupnews'; // Required - Replace example with your forum shortname
			 var disqus_identifier = '{% if article.disqus_id %}{{article.disqus_id}}{%else%}GU2_{{article.pk}}{% endif %}';
			 var disqus_url = '{{ request.build_absolute_uri }}';

			 /* * * DON'T EDIT BELOW THIS LINE * * */
			 (function() {
			     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
			     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
			     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			 })();
			</script> <noscript>Please enable JavaScript to view the <a href=
										    "http://disqus.com/?ref_noscript">comments powered by
			    Disqus.</a></noscript> <a class="dsq-brlink" href=
						      "http://disqus.com">Comments powered by <span class="logo-disqus">Disqus</span></a>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>

newsroom/templates/newsroom/article_letters.html
<div class="letters" id="letters">
    {% if article.letters_on %}
	<div class="article__letter__button">
	  <a class="article__letter__link" href="{% url "letter_to_editor" article.pk %}">
	    Write a letter in response to this article
	  </a>
	</div>
    {% endif %}

    {% if article_letters %}
      <a name="letters-to-editor"></a>
      <h2 class="letters-header">Letters</h2>
      <div class="panel-group" id="letter-accordion">
	{% for letter in article_letters %}
	  <a name="letter-{{letter.pk}}"></a>
	  <div class="panel panel-default">
	    <div class="panel-heading">
	      <h4 class="panel-title">
		<a data-toggle="collapse"
		   data-parent="#letter-accordion"
		   href="#letter-{{forloop.counter}}"
		   class="{{letter.css_classes}}">
		  {{letter.title}}
		</a>                
	      </h4>
	    </div>
	    <div id="letter-{{forloop.counter}}"
		 class="panel-collapse collapse in">
	      <div class="panel-body">
		<div class="letter">
                  {% include "letters/letter_text.html" %}
                  {% if can_edit %}
                    <a href="{% url 'admin:letters_letter_change' letter.pk %}">
                      Edit letter
                    </a>
                  {% endif %}
		</div>
	      </div>
	    </div>
	  </div>
	{% endfor %}
      </div>
    {% endif %}
</div>

newsroom/templates/newsroom/article_list_form.html
{% extends 'base.html' %}

{% block title %}
    Generate newsletter {{block.super}}
{% endblock %}

{% block additional_head %}

    {{block.super}}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/css/bootstrap-datetimepicker.min.css"></link>

{% endblock %}

{% block content %}

    <div class="container">
	<div class="row">
	    <div class="col-sm-8 col-md-offset-2">
    <h1>Generate a list of articles</h1>
    <form role="form" action="{% url 'generate_article_list' %}" method="post">
	{% csrf_token %}

	{{ form.non_field_errors }}


        <div class="form-group">

	    <label for="id_date_from">Date from (required):</label>
	    {% for error in form.date_from.errors %}
		<p class="alert alert-danger">{{ error }}</p>
	    {% endfor %}
            <div class='input-group date' id='datetimepicker1'>
		<input id="id_date_from" name="date_from"
		       type='text' class="form-control" />
		<span class="input-group-addon">
		    <span class="glyphicon glyphicon-calendar"></span>
		</span>
	    </div>
        </div>


        <div class="form-group">
	    <label for="id_date_to">Date to:</label>
	    {% for error in form.date_to.errors %}
		<p class="alert alert-danger">{{ error }}</p>
	    {% endfor %}
            <div class='input-group date' id='datetimepicker2'>
		<input id="id_date_to" name="date_to"
		       type='text' class="form-control" />
		<span class="input-group-addon">
		    <span class="glyphicon glyphicon-calendar"></span>
		</span>
            </div>
        </div>

	<div class="form-group">
	    <input type="submit" value="Generate" class="btn btn-default">
	</div>


    </form>

    {% if output %}
	<div class="row">
	    <div class="col-md-3"></div>
	    <div class="col-md-6" style="text-align: center; margin:10px; padding:10px;">
		<p class="alert alert-info">{{len_articles}} articles.</p>
	    </div>
	</div>
	<div class="row">
	    <div class="col-md-6">
		<div class="form-group">
		    <textarea class="form-control" rows="25" style="margin-top:15px;">{% for	  line in output %}{{line}}
{% endfor %}</textarea>
		</div>
	    </div>
	    <div class="col-md-6" style="border: 2px solid; margin-top: 15px;">
		{% for line in output %}
		    {{line|safe}}
		{% endfor %}
	    </div>
	</div>
    {% endif %}
	    </div>
	</div>
    </div>
{% endblock %}


{% block javascript-includes %}
    {{block.super}}
    <script type="text/javascript"	src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js">
    </script>
    <script type="text/javascript"	src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript">
     $(function () {
	 $('#datetimepicker1').datetimepicker({
	     format:'YYYY-M-D HH:mm'
	 });
     });
    </script>
    <script type="text/javascript">
     $(function () {
	 $('#datetimepicker2').datetimepicker({
	     format:'YYYY-M-D HH:mm'
	 });
     });
    </script>
{% endblock %}

newsroom/templates/newsroom/article_summary.html
<div class="home__articles__article">
  {% if article.cached_summary_image %}
    <div class="home__articles__article__image summary-image-container">
      <a style="display:block;" href="{{article.get_absolute_url}}">
	<img class="summary-image"
	     src="{{ article.cached_summary_image }}"
	     alt="{{ article.summary_image_alt }}"/>
      </a>
    </div>
  {% endif %}

  <div class="home__articles__article__text">
    <div class="home__articles__article__text__box">
      <a href="{{article.get_absolute_url}}">
	<p class="home__articles__article__text__category">
	  {{article.category|upper}}
	</p>
      </a>
      <a href="{{article.get_absolute_url}}">
	<p class="home__articles__article__text__date">
	  {{article.published|date:"j F Y"}}
	</p>
      </a>
      <h2 class="home__articles__article__text__title">
	<a href="{{article.get_absolute_url}}">
	  {{article.title|safe }}
	</a>
      </h2>
      {% if include_summary == "1" %}
	<a href="{{article.get_absolute_url}}">
	  <p class="home__articles__article__text__summary"">
	    {{article.cached_summary_text|safe}}
	  </p>
	</a>
      {% endif %}
      <p class="home__articles__article__text__byline">
	<a href="{{article.get_absolute_url}}">
	  {{article.cached_byline_no_links|safe|striptags}}
	</a>
      </p>
      <div class="home__articles_article__details-mobile">
        <a href="{{article.get_absolute_url}}">
          {{article.cached_byline_no_links|safe|striptags}}
	</a> - {{article.published|date:"j F Y"}}
      </div>
    </div>
  </div>
</div>

newsroom/templates/newsroom/article_topics.html
<div class="article__topics">
  <span class="article__topics__header">TOPICS:&nbsp;</span>
  {% with topics_all=article.topics.all %}
    {% if topics_all|length  %}
      {% for topic in topics_all %}
	<a class="article__topic" href="{% url 'topic.detail' topic.slug %}">
          {{ topic.name|capfirst }}</a>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>

newsroom/templates/newsroom/home.html
{% extends 'newsroom/article_list.html' %}

{% block title %}
  GroundUp: South African news that matters
{% endblock %}

{% block article-list %}
  <div class="home" id="list-content">
      {% include 'blocks/blocks.html' with blocks=topblocks%}
    <div class="home_container">
      <div  class="home__article-list">
	{% if page_obj.has_previous or article_list.0.stickiness == 0 %}
	  {% include 'newsroom/list.html' with articles=article_list include_image="1" include_summary="1" md_size="12" %}
	{% else  %}
	  {% with article_list.0 as article %}
	    <div class="home__top-article" id="top-article">
              <div class="home__top-article_image">
		<a href="{{article.get_absolute_url}}">
		  <img class="first-summary-image
			      summary-image"
		       src="{{ article.cached_primary_image }}"
		       alt="{{ article.summary_image_alt }}"/>
		</a>
              </div>

              <div class="home__top-article_text">
                <div class="home__top-article_text__box">
                  <div class="home__top-article_text__category">
                    {{article.category|upper}}
                  </div>
                  <div class="home__top-article_text__date">
                    {{article.published|date:"j F Y"}}
                  </div>
		  <h2 class="home__top-article_text__title">
		    <a href="{{article.get_absolute_url}}">
		      {{article.title|safe }}
		    </a>
		  </h2>
		  <div class="home__top-article_text__summary">
		    <a href="{{article.get_absolute_url}}">
		      {{article.cached_summary_text|safe}}
		    </a>
		  </div>
                  <div class="home__top-article_text__byline">
                    <a href="{{article.get_absolute_url}}">
		      {{article.cached_byline_no_links|safe|striptags}}
		    </a>
                  </div>
                  <div class="home__top-article_text__details-mobile">
                    <a href="{{article.get_absolute_url}}">
                      {{article.cached_byline_no_links|safe|striptags}}
		    </a> - {{article.published|date:"j F Y"}}
                 </div>
                </div>
              </div>
	    </div>
	  {% endwith %}
	  {% with article_list|slice:"1:" as articlelist %}
	    {% include 'newsroom/list.html' with articles=articlelist include_image="1" include_summary="1" md_size="12" %}
	  {% endwith %}
	{% endif %}
        {% include 'paginator.html' %}
      </div>
    </div>
    <div class="more_articles">
      <div class="more_articles__popular">
        <h2>Most Read</h2>
        {{most_popular_html|safe}}
      </div>
      <div class="more_articles__letters">{% include 'letters/letters.html' %}</div>
    </div>
    {% include 'newsroom/social_media.html' %}
  </div>
{% endblock %}

newsroom/templates/newsroom/read_similar.html
{% if related %}
<div id="related">
    {% for rel_article in related %}
        {% if forloop.first %}
            <h3>More about <a href="{% url 'topic.detail' article.main_topic.slug %}">
                {{article.main_topic}}</a></h3>
            <ul>
        {% endif %}
        <li>
            <a href="{{rel_article.get_absolute_url}}">
                {{rel_article.title}}</a> <span class="related-date">{{rel_article.published|date:"d F Y" }}</span>
        </li>
        {% if forloop.last %}
            </ul>
        {% endif %}
    {% endfor %}
</div>
{% endif %}